# Generated by Django 6.0 on 2025-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Difficulty level of question when user attempted it', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='current_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Adaptive difficulty for the active quiz attempt', max_length=10),
        ),
    ]
